### PR TITLE
Fix minimap index issue with large genomes  #30 

### PR DESCRIPTION
**Pull request by gemygk**
Thanks @ljyanesm for adding the changes.

I will merge this into main.

### CODE REVIEW

**Comment by ljyanesm** [comment]
Is there a chance you could spend a bit of time checking why the pipeline
failed? I suspect the parameter may be causing mm2 to use more memory and
its not completing correctly now, but haven't had a chance to check.

**Comment by gemygk** [comment]
As David mentioned in the issue #30, minimap2 creates multi-part index when the genome is greater than 4Gbs (which is the default) causing mangled SAM headers. When David tested it, increasing `-I 128G` keeps the same single index as before and minimap2 works fine. The memory used to index Wheat using Hisat was ~100-125Gb and with minimap2 is ~90-100Gb, which is expected in this case.

Having said that, I have not tried to fix the  SAM headers with `--split-prefix` (with any additional steps as required) which would be ideal to do at a later stage.

**Comment by ljyanesm** [comment]
Sorry, my bad didn't realise the pipeline error was an indentation issue.
You've already fixed this.

Many thanks!

**Comment by gemygk** [comment]
Oh yes, I thought you were talking about the actual pipeline 🙂.

**Pull request merged**
